### ISSUE TITLE
can't find device and initialization files

### ISSUE THREAD

**Issue by spiricom** [kiml/PSOC_programmer#4]
After compiling on OSX (thanks to the other user for the hint on adding an include to getopt.h - it seems the main repository doesn't include the fit yet), I get an error when attempting to load a hex file. It seems like it can't find the .dev and .ini files. I'm not sure how to point to them - they are in a folder called config, and I've tried that folder living one level up from /bin and also inside /bin and neither worked. 

$ ./prog program testfile_1.hex
Device Name not specified
Failed to read device config

Also, thanks for this work! I am hoping I can get it working so I will have a simple way to program hex files onto the CY8Ckit-059 (possibly compatible? can't tell if it uses the same kitprog IC) using a Mac for teaching purposes with students who don't have Windows machines.

**Comment by spiricom** [comment]
Reading more into the source, I'm guessing this repo doesn't really do what I need (though this is an impressive undertaking!) - seems like perhaps the programming part of it expects hex files creating using this free hex format, where I'm just trying to program hex files from PSOC Creator after transferred the hex file to a Mac. 
Don't worry about answering if this use case isn't part of your scope.

**Comment by lowfatcomputing** [comment]
openocd supports the PSoC 5LP with some patches. See http://www.psoctools.org/psoc5lp-tools.html

**Comment by spiricom** [comment]
ah - fantastic! That's something I hadn't been able to find.
